globalCouponEngine/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("promotion.urls", namespace="Promotion")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

promotion/urls.py
from django.urls import path
from . import views
import os

app_name = "Promotion"

urlpatterns = [
    path("", views.homepage, name="Homepage"),
    path("<slug:target_country_slug>/", views.country_page, name="Country"),
    path("<slug:target_country_slug>/<slug:target_brand_slug>/", views.brand_page, name="Brand")
]

promotion/models.py
from datetime import datetime
from django.utils.text import slugify
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator


def rename_country_logos(instance, filename):
	filebase, extension = filename.split('.')
	if instance.pk:
		return "images/country_flags/{}.{}".format(slugify(instance.pk), extension)
	else:
		return "images/country_flags/{}.{}".format(instance.country_slug, extension)


def rename_brand_logo(instance, filename):
	filebase, extension = filename.split('.')
	if instance.pk:
		return "images/brand_logos/{}.{}".format(slugify(instance.pk), extension)
	else:
		return "images/brand_logos/{}.{}".format(instance.brand_slug, extension)


class Country(models.Model):
	country_name = models.CharField(max_length=50, unique=True, verbose_name="Name")
	country_slug = models.SlugField(editable=False)
	country_logo = models.FileField(upload_to=rename_country_logos, verbose_name="Logo")
	
	class Meta:
		verbose_name = 'Country'
		verbose_name_plural = 'Countries'
		ordering = ['country_name']
		
	def save(self, *args, **kwargs):
		self.country_slug = slugify(self.country_name)
		super(Country, self).save(*args, **kwargs)
		
	def get_absolute_url(self):
		return reverse("Promotion:Country", args=[self.country_slug])
		
	def __str__(self):
		return self.country_name


class Brand(models.Model):
	exists_in = models.ManyToManyField(Country, verbose_name='Countries')
	brand_name = models.CharField(max_length=50, unique=True, verbose_name="Name")
	brand_slug = models.SlugField(editable=False)
	brand_logo = models.FileField(upload_to=rename_brand_logo, verbose_name="Logo")
	brand_link = models.CharField(max_length=200, verbose_name="URL")
	
	class Meta:
		ordering = ['brand_name']
		
	def save(self, *args, **kwargs):
		self.brand_slug = slugify(self.brand_name)
		super(Brand, self).save(*args, **kwargs)
	
	def __str__(self):
		return self.brand_name


class Offer(models.Model):
	choices_offer_type = [
		("CODE", "Code"),
		("DEAL", "Deal"),
	]
	validators_offer_amount = [
		MinValueValidator(0),
		MaxValueValidator(100),
	]
	offer_title = models.CharField(max_length=50, verbose_name="Title")
	offer_details = models.TextField(max_length=300, verbose_name='Description')
	offered_by = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='Brand')
	offered_in = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='Country')
	offer_type = models.CharField(max_length=4, choices=choices_offer_type, verbose_name="Type")
	offer_amount = models.IntegerField(validators=validators_offer_amount, verbose_name='Amount')
	offer_code = models.CharField(max_length=30, verbose_name="Code", help_text="Leave this field empty for deals.", default="You don't need any code!")
	offer_expires_on = models.DateField(verbose_name='Expires On')
	offer_next_available_on = models.DateField(verbose_name='Next Available On')
	offer_created_on = models.DateTimeField(auto_now_add=True, verbose_name='Created On')
	offer_last_updated_on = models.DateTimeField(auto_now=True, verbose_name='Last Updated On')
	
	class Meta:
		ordering = ['-offer_last_updated_on', '-offer_created_on']
	
	def is_expired(self):
		if datetime.today() > self.offer_expires_on:
			return True
		return False
	
	def __str__(self):
		return self.offer_title


class Comment(models.Model):
	username = models.CharField(max_length=50, verbose_name="Username")
	comment = models.TextField(max_length=1000, verbose_name='Comment')
	comment_created_on = models.DateTimeField(auto_now_add=True)
	comment_last_updated_on = models.DateTimeField(auto_now=True)
	
	class Meta:
		ordering = ['-comment_last_updated_on', '-comment_created_on']
		
	def __str__(self):
		return str(self.username) + ", " + str(self.comment_created_on)
		

promotion/views.py
from django.shortcuts import render
from promotion.models import Country, Brand, Offer, Comment
from datetime import date

def homepage(request):
	countries = Country.objects.all()
	context = {"countries": countries}
	render(request, "country_list_footer.html", context)
	return render(request, "homepage.html", context)


def country_page(request, target_country_slug):
	target_country = Country.objects.get(country_slug=target_country_slug)
	brands = Brand.objects.filter(exists_in=target_country)
	offers = Offer.objects.filter(offer_expires_on__gte=date.today(), offered_in=target_country)
	context = {"target_country": target_country, "brands": brands, "offers": offers}
	return render(request, "country_page.html", context)


def brand_page(request, target_country_slug, target_brand_slug):
	target_country = Country.objects.get(country_slug=target_country_slug)
	target_country_brands = Brand.objects.filter(exists_in=target_country)
	target_brand = Brand.objects.get(brand_slug=target_brand_slug)
	available_offers = Offer.objects.filter(offer_expires_on__gte=date.today(), offered_by=target_brand, offered_in=target_country)
	expired_offers = Offer.objects.filter(offer_expires_on__lte=date.today(), offered_by=target_brand, offered_in=target_country)
	comments = Comment.objects.all()
	current_month_year = date.today().strftime("%B") + ", " + date.today().strftime("%Y")
	context = {"target_country": target_country, "target_country_brands": target_country_brands, "target_brand": target_brand, "available_offers": available_offers, "expired_offers": expired_offers, "comments": comments, "current_month_year": current_month_year}
	return render(request, "brand_page.html", context)

templates/base_footer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block Stylesheet %}
    {% endblock %}

    <title>
        {% block Title %}
        {% endblock %}
    </title>
</head>

<body>
    {% block Content %}
    {% endblock %}

    {#PICODI FOOTER START#}
    <footer>
        <div class="container-fluid bg-dark text-light">
            <div class="row mx-2 mb-2 p-4">
                <div class="col-md-2 mx-4"></div>
                <div class="col-md-3 p-2">
                    <div class="row m-4">
                        <div class="col-md p-2">
                            <a href="#"><img height="64" width="128" src="{% static 'promotion/vectors/funscrimp_logo.svg' %}" alt="Funscrimp_company_logo"></a> {# FUNSCRIMP LOGO #}
                        </div>
                    </div>
                    <div class="row m-4">
                        <div class="col-md p-2">
                            <p>Funscrimp is a virtual shopping software that helps millions around the world save money when they purchase online. Navigate through a wide range of offers from your favorite merchants or discover whole new shopping locations. Having everything else in one location is simple and convenient!</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-3 p-2">
                    <div class="row m-4">
                        <div class="col-md px-2 py-4">
                            <h5>CONTACT</h5>
                        </div>
                    </div>
                    <div class="row m-4">
                        <div class="col-md p-2">
                            <p class="my-0">Funscrimp.com</p>
{#                            <p class="my-0">Przemysłowa 12</p>#}
{#                            <p class="my-0">30-701 Cracow, Poland</p>#}
                            <p class="my-0"><b>contact@funscrimp.com</b></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 mx-4"></div>
            </div>
            <div class="row p-4 text-center vstack">
                <div class="col-md p-4 border-top border-light">
                    <p>© 2022 Copyright - Funscrimp - All rights reserved.</p>
                </div>
{#                <div class="col-md p-4">#}
{#                    <div class="row justify-content-center">#}
{#                        <div class="col-1 p-2">#}
{#                            <a href="#"><img height="32" width="32"  src="{% static 'promotion/vectors/fb_logo.svg' %}" alt=""></a>#}
{#                        </div>#}
{#                        <div class="col-1 p-2">#}
{#                            <a href="#"><img height="32" width="32" src="{% static 'promotion/vectors/twitter_logo.svg' %}" alt=""></a>#}
{#                        </div>#}
{#                        <div class="col-1 p-2">#}
{#                            <a href="#"><img height="32" width="32" src="{% static 'promotion/vectors/insta_logo.svg' %}" alt=""></a>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
    </footer>
    {# PICODI FOOTER END #}

    <script type="text/javascript" src="{% static 'promotion/js/global_script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>

</html>

templates/country_list_footer.html
{% load static %}

<div class="container-fluid" id="picodi_country_list">
    <div class="container">
        <div class="row mx-2 mb-2 p-4">
            {% for country in countries %}
                <div class="col-md-2 p-2 hstack">
                    <img height="24" width="32" class="img-fluid border rounded" src="{% get_media_prefix %}{{ country.country_logo }}" alt="Funscrimp_country_flag">
                    <a href="{{ country.get_absolute_url }}" class="link-dark m-2 text-decoration-none">{{ country.country_name }}</a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/country_page.html
{% extends "base_footer.html" %}
{% load static %}

{% block Stylesheet %}
    <link href="{% static 'promotion/css/country_page.css' %}" rel="stylesheet">
    <link href="{% get_media_prefix %}{{ target_country.country_logo }}" rel="icon">
{% endblock %}

{% block Title %}
    Funscrimp: {{ target_country }}
{% endblock %}

{% block Content %}
    {% include "navbar_header.html" %}

    <div class="container-fluid border-top border-bottom border-dark">
        <div class="row border">
            <div class="collapse bg-white rounded" id="search_brands">
                <div class="p-2" id="result_brands">
                    {% for brand in brands %}
                        <div class="row m-2 brand_as_search_result" brand_name="{{ brand.brand_name }}">
                            <div class="col-auto align-self-center">
                                <a href="{{ brand.brand_slug }}">
                                    <img class="img-fluid rounded" height="36" width="48" src="{% get_media_prefix %}{{ brand.brand_logo }}" alt="Funscrimp_brand_logo">
                                </a>
                            </div>
                            <div class="col-auto align-self-center">
                                <a href="{{ brand.brand_slug }} " class="link-dark text-decoration-none">
                                    {{ brand.brand_name }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid p-4 text-light border-bottom border-dark" id="country_page_sub_header">
        <div class="row px-4 pt-4 justify-content-center">
            <div class="col-md-auto">
                <h1 class="text-dark">
                    Get all the fun of online deals in one place!
                </h1>
            </div>
        </div>
        <div class="row p-4 justify-content-center">
            <div class="col-md-auto">
                <h4 class="text-dark">
                    Cashback, coupons and promo codes for all shops and brands in {{ target_country.country_name }}.
                </h4>
            </div>
        </div>
    </div>

    <div class="container-fluid p-4 bg-light border-bottom border-dark">
        <div class="container p-4">
            <div class="row px-2">
                <div class="col-md">
                    <h4>Brands</h4>
                </div>
            </div>
            <div class="row p-2" id="brands_section">
                {% for brand in brands %}
                    <div class="col-lg-3">
                        <div class="container my-2 py-2 bg-white border rounded-3">
                            <div class="row justify-content-center">
                                <div class="col-md-auto text-center">
                                    <a href="{{ brand.brand_slug }}">
                                        <img height="96" width="128" src="{% get_media_prefix %}{{ brand.brand_logo }}" alt="Funscrimp_brand_logo">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid p-4 bg-light border-bottom border-dark">
        <div class="container px-2 pb-2 bg-light">
            <div class="row px-2">
                <div class="column-md">
                    <h4>Trending Now</h4>
                </div>
            </div>
            <div class="row p-2">
                {% for offer in offers %}
                    <div class="col-lg-3 my-2">
                        <div class="container py-2 bg-white h-100 border rounded-3">
                            <div class="row my-4 justify-content-center">
                                <div class="col-md-auto text-center">
                                    <a href="{{ offer.offered_by.brand_slug }}">
                                        <img height="111" width="148" src="{% get_media_prefix %}{{ offer.offered_by.brand_logo }}" alt="Funscrimp_brand_logo">
                                    </a>
                                </div>
                            </div>
                            <div class="row my-4 justify-content-center">
                                <div class="coll-md-auto text-center">
                                    <h5>{{ offer.offer_title }}</h5>
                                </div>
                            </div>
                            <div class="row my-4 justify-content-center">
                                <div class="col-md-auto text-center">
                                   {% if offer.offer_type == "CODE" %}
                                       <a class="btn btn-danger btn-outline-light px-4 rounded-pill" coupon_no="{{ forloop.counter0 }}" c_percentage="{{ offer.offer_amount }}" c_type="{{ offer.offer_type }}" c_title="{{ offer.offer_title }}" c_details="{{ offer.offer_details }}" c_code="{{ offer.offer_code}}" c_link="{{ offer.offered_by.brand_link }}" onclick="redirect_hidden({{ forloop.counter0 }}); set_href_brand_name(`{{ offer.offered_by.brand_name }}`, '{{ offer.offered_by.brand_link }}');" href="#" role="button" id="button_code" data-bs-toggle="modal" data-bs-target="#code_modal"><b>REVEAL THE CODE</b></a>
                                   {% endif %}
                                    {% if offer.offer_type == "DEAL" %}
                                        <a class="btn btn-warning btn-outline-light px-5 rounded-pill" coupon_no="{{ forloop.counter0 }}" c_percentage="{{ offer.offer_amount }}" c_type="{{ offer.offer_type }}" c_title="{{ offer.offer_title }}" c_details="{{ offer.offer_details}}" c_code="You do not need any code for this offer!" c_link="{{ offer.offered_by.brand_link }}" onclick="redirect({{ forloop.counter0 }}); set_href_brand_name(`{{ offer.offered_by.brand_name }}`, '{{ offer.offered_by.brand_link }}');" href="#" role="button" id="button_deal" data-bs-toggle="modal" data-bs-target="#code_modal"><b>GET THE DEAL</b></a>
                                    {%  endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="modal fade" id="code_modal" tabindex="-1" aria-labelledby="code_modal_label" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-lg">
                        <div class="modal-content p-4">
                            <div class="modal-header border border-dark rounded-3">
                                <h5 class="modal-title" id="code_modal_label">Congratulations!</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row mb-2">
                                    <div class="col-md-3">
                                        <div class="row">
                                            <div class="col-md">
                                                <div class="row">
                                                    <div id="popup_percentage_back">
                                                        <h1><b id="popup_percentage_target"></b></h1>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div id="popup_type_back">
                                                        <p class="text-center text-light"><b id="popup_type_target"></b></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md rounded-3">
                                                <p class="text-center"><b id="popup_title_target"></b></p>
                                                <p class="text-center" id="popup_details_target"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <div class="col-md">
                                        <div class="row px-6 bg-dark text-light border border-dark rounded-3">
                                            <div class="col-md py-3 border-dark rounded-3">
                                                <h3 class="text-center">
                                                    <b id="popup_code_target"></b>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer justify-content-center">
                                <div class="row align-items-center justify-content-center">
                                    <div class="col-md self-align-center text-center">
                                        <a href="" type="button" class="btn btn-lg btn-success btn-outline-light rounded-pill" id="popup_button"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "how_does_funscrimp_work.html" %}
{% endblock %}

templates/homepage.html
{% extends "base_footer.html" %}
{% load static %}

{% block Stylesheet %}
    <link href="{% static 'promotion/css/homepage.css' %}" rel="stylesheet">
    <link href="{% static 'promotion/vectors/funscrimp_logo.svg' %}" rel="icon">
{% endblock %}

{% block Title %}
    Funscrimp: Home
{% endblock %}

{% block Content %}
    <div class="container-fluid border-bottom border-dark bg-dark text-light" id="homepage_header">
        <div class="row mx-2 p-4 justify-content-start">
            <div class="col-md p-2">
                <a href="#"><img height="64" width="128" src="{% static 'promotion/vectors/funscrimp_logo.svg' %}" alt="Funscrimp_company_logo"></a>
            </div>
        </div>
        <div class="row mx-2 p-4 justify-content-center">
            <div class="col-md text-center">
                <h1 class="text-dark"><b>Get all the fun of online deals in one place!</b></h1>
            </div>
        </div>
{#        <div class="row mx-2 p-4 justify-content-center">#}
{#            <div class="col-md text-center">#}
{#                <h5><b>The best online deals just one click away!</b></h5>#}
{#            </div>#}
{#        </div>#}
        <div class="row mx-2 p-4 justify-content-center">
            <div class="col-md-auto mx-0 p-0 text-center">
                <button class="btn btn-light btn-lg border-dark" type="button" data-bs-toggle="collapse" data-bs-target="#search_countries" aria-expanded="false" aria-controls="search_countries"><img class="mr-2" height="32" width="32" src="{% static 'promotion/images/globe.png' %}" alt="Funscrimp_search_country"><b class="p-2">&nbsp;&nbsp;Select a country to search for discounts</b></button>
                <div class="collapse bg-white border border-dark rounded" id="search_countries">
                    <form class="d-flex">
                        <label for="country_search"></label>
                        <input class="form-control form-control-lg my-2 border-top-0 border-start-0 border-end-0 border-dark" id="country_search" type="search" placeholder="Search..." onkeyup="live_search_country()">
                    </form>
                    <div class="p-2" id="result_countries">
                        {% for country in countries %}
                            <div class="row m-2 country_as_search_result" country_name="{{ country.country_name }}">
                                <div class="col-auto">
                                    <a href="{{ country.get_absolute_url }}">
                                        <img class="img-fluid rounded" height="24" width="32" src="{% get_media_prefix %}{{ country.country_logo }}" alt="Funscrimp_country_flag">
                                    </a>
                                </div>
                                <div class="col-auto">
                                    <a href="{{ country.get_absolute_url }} " class="link-dark text-decoration-none">
                                        {{ country.country_name }}
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row mx-2 p-4 justify-content-center">
            <div class="col-md p-4 vstack align-items-center text-center">
                <img class="img-fluid" height="256" width="256" src="{% static 'promotion/vectors/funscrimp_money.svg' %}" alt="Funscrimp_mascot">
                <h4 class="text-dark">Hey there!</h4>
                <p class="text-dark">I'm your currency! Save me please!</p>
                <a href="#lets_explore_funscrimp"><button class="btn btn-outline-dark btn-lg m-2 text-dark" id="explore_funscrimp">Let's Explore Funscrimp!</button></a>
{#                <a href="#picodi_country_list"><button class="btn btn-outline-light btn-lg m-2">&nbsp;&nbsp;Country&nbsp;&nbsp;List&nbsp;&nbsp;</button></a>#}
            </div>
        </div>
    </div>

    <div class="container-fluid border-bottom border-dark" id="lets_explore_funscrimp">
        <div class="row m-2 p-4 align-items-center">
            <div class="col-lg-4 p-4 text-center">
                <img src="{% static 'promotion/vectors/funscrimp_money.svg' %}" class="img-fluid" alt="Funscrimp_doodle">
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-6 p-4">
                <h1>Wondering how I can be saved!</h1>
                <p>Join <b>Funscrimp</b> and use it <b>every</b> time you desire to shop <b>online.</b></p>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light border-bottom border-dark">
        <div class="row m-2 p-4 flex-column-reverse flex-lg-row align-items-center">
            <div class="col-lg-6 p-4">
                <h1> Looking for Discount to save me?</h1>
                <h2>Let me show how!</h2>
                <p>With <b>Funscrimp,</b> it's <b>fun</b> to find online discounts. If you are facing trouble to <b>save</b> your money, find the <b>best</b> bargains on the web while visiting <b>Funscrimp.</b></p>
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-4 p-4 text-center">
                <img src="{% static 'promotion/vectors/funscrimp_money01.svg' %}" class="img-fluid" alt="Funscrimp_doodle">
            </div>
        </div>
    </div>

    <div class="container-fluid border-bottom border-dark">
        <div class="row m-2 p-4 align-items-center">
            <div class="col-lg-4 text-center">
                <img src="{% static 'promotion/vectors/funscrimp_money02.svg' %}" class="img-fluid" alt="Funscrimp_doodle">
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-6">
                <h1>I am everywhere!</h1>
                <p>You can find me at your favorite retailers. Don't miss <b>discounts</b> from your <b>favorite</b> stores. Browse a wide selection of online deals from popular brands or find entirely new shopping destinations.</p>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light border-bottom border-dark">
        <div class="row mx-2 mt-2 p-4 flex-column-reverse flex-lg-row align-items-center">
            <div class="col-lg-6">
                <h1>Now you can save me!</h1>
                <p><b>Smart</b> people like you from <b>{{ countries|length }}+</b> countries across the globe can now enjoy <b>Funscrimp.</b> And I will be not lost now as smart people like you saved me! Saving me is fun, right? Thanks, <b>buddy!</b></p>
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-4 text-center">
                <img src="{% static 'promotion/vectors/funscrimp_money03.svg' %}" class="img-fluid" alt="Funscrimp_doodle">
            </div>
        </div>
    </div>

    {% include "country_list_footer.html" %}
{% endblock %}

templates/navbar_header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand px-4" href="{% url 'Promotion:Homepage' %}"><img height="48" width="96" src="{% static 'promotion/vectors/funscrimp_logo.svg' %}" alt="Funscrimp_company_logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Top Deals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Expiring Deals</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Join
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Sign in</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Sign up</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2 rounded-pill" id="brand_search" type="search" placeholder="Search for brands..." aria-label="Search" data-bs-toggle="collapse" data-bs-target="#search_brands" aria-expanded="false" aria-controls="search_brands" onkeyup="live_search_brands()">
            </form>
        </div>
    </div>
</nav>